version: "3.7"
services:
  idp:
    ports:
      - "9000:9000"
    build:
      context: idp
      dockerfile: Dockerfile


  metric-server:
    environment:
      MONGO_USERNAME: "root"
      MONGO_PASSWORD: "root"
      MONGO_CLUSTER_ENDPOINT: "mongo"
    ports:
      - "8080:8080"
    build:
      context: metric-server
      dockerfile: Dockerfile
    depends_on:
      - idp
      - mongo

  metric-ui:
    environment:
      ID_HOST: "http://idp:9000"
      METRIC_SERVE_HOST: "http://metric-server:8080"
    build:
      context: metric-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - metric-server

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./metric-server/init.js:/docker-entrypoint-initdb.d/init.js:ro