logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: debug
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://idp:9000
  data:
    mongodb:
      uri: mongodb://root:example@mongo:27017/db?authSource=admin
      database: factorial